# Generated by Django 5.1.3 on 2024-11-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('acoes', models.CharField(max_length=100, null=True)),
                ('imagem', models.FileField(null=True, upload_to='imagem_admins')),
            ],
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(null=True, upload_to='imagem_alunos')),
                ('serie', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('eletiva', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descricao', models.TextField(max_length=73)),
                ('imagem', models.ImageField(upload_to='img_anuncio/')),
                ('link', models.URLField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarrosselProfessores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Eletivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=150)),
                ('imagem', models.ImageField(upload_to='img_eletivas/')),
                ('link', models.URLField(max_length=100, null=True)),
                ('img_professores_eletiva', models.ImageField(null=True, upload_to='img_eletivas/img_professores_eletiva')),
            ],
        ),
        migrations.CreateModel(
            name='OqueTemosaOferecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=76)),
                ('imagem', models.ImageField(upload_to='img_OqueTemosaOferecer/')),
                ('link', models.URLField()),
                ('titulo_do_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaginasUtilizaveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutoria', models.BooleanField()),
                ('eletiva', models.BooleanField()),
                ('index', models.BooleanField()),
                ('sobre', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eletiva', models.CharField(max_length=100, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('idade', models.IntegerField()),
                ('imagem', models.FileField(null=True, upload_to='imagem_professores')),
                ('professor', models.BooleanField(null=True)),
                ('tutor', models.BooleanField(null=True)),
                ('descricao', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
