# Generated by Django 5.0.6 on 2024-11-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0014_paginasutilizaveis_sobre'),
    ]

    operations = [
        migrations.CreateModel(
            name='OqueTemosaOferecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=200)),
                ('imagem', models.ImageField(upload_to='img_OqueTemosaOferecer/')),
                ('link', models.URLField()),
                ('titulo_do_link', models.CharField(max_length=100)),
            ],
        ),
    ]
