# Generated by Django 5.0.6 on 2024-11-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0015_oquetemosaoferecer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oquetemosaoferecer',
            name='descricao',
            field=models.TextField(max_length=76),
        ),
    ]
