# Generated by Django 5.0.6 on 2024-11-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0017_carrosselprofessores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrosselprofessores',
            name='ids',
        ),
        migrations.AddField(
            model_name='carrosselprofessores',
            name='descricao',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carrosselprofessores',
            name='graduacao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carrosselprofessores',
            name='idade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carrosselprofessores',
            name='imagem',
            field=models.FileField(null=True, upload_to='carrosselProfessores/'),
        ),
        migrations.AddField(
            model_name='carrosselprofessores',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
