# Generated by Django 5.0.6 on 2024-11-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0019_carrosseldosprofessores_delete_carrosselprofessores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarrosseldosProfessores',
            new_name='CarrosselProfessores',
        ),
    ]
