# Generated by Django 5.1.1 on 2024-11-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0020_rename_carrosseldosprofessores_carrosselprofessores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrosselprofessores',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
    ]
