# Generated by Django 5.0.6 on 2024-11-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0020_rename_carrosseldosprofessores_carrosselprofessores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='descricao',
            field=models.TextField(max_length=73),
        ),
    ]
